const DICTIONARIES = {
  en: {
    languageLabel: 'Language', heroEyebrow: 'TRAIN YOUR COMPETITION MEMORY', heroTitle1: 'See the code.', heroTitle2: 'Know the dive.', heroCopy: 'Practice the letters, blocks and formations in your dive pool. On your phone, tablet or computer.',
    tabTrain: 'Train', tabLibrary: 'Figure library', tabSettings: 'Settings', sectionTrain: '01 / TRAIN', trainHeading: 'Your next dive', randomCombination: 'RANDOM COMBINATION', revealButton: 'Show figures', resetButton: 'Restart pool',
    sectionLearn: '02 / LEARN', libraryHeading: 'Figure library', libraryCopy: 'Explore the name and drawing of every letter and block in your selected pool.', searchLabel: 'Search figure or name', searchPlaceholder: 'Search code or name…', filterAll: 'All', filterLetters: 'Letters', filterBlocks: 'Blocks',
    sectionSettings: '03 / SETTINGS', settingsHeading: 'Make it your training', poolLabel: 'Dive pool', poolHelp: 'Changing the pool starts a new training session.', difficultyLabel: 'Difficulty', difficultyHelp: 'The combination continues until it reaches this many points. A block counts as two.', delayLabel: 'Figure delay', delayHelp: 'The images appear automatically after this delay. You can show them sooner with “Show figures”.', saveButton: 'Save settings', footer: 'Train independently · No account needed · Works offline after your first visit',
    ready: 'Ready to start', startHint: 'Press GO to get a new combination.', round: 'Round {count}', remaining: '{count} figures left', target: 'Target: {points}', poolFinished: 'Pool complete. Restart for a new series.', rememberOne: 'Remember the figure behind this code.', rememberMany: 'Remember the figures behind these codes.', appearing: 'The figures will appear shortly…', shownOne: '1 figure shown. Tap the image to enlarge it.', shownMany: '{count} figures shown. Tap an image to enlarge it.', libraryCount: '{count} of {total} figures', onePoint: '1 point', manyPoints: '{count} points', seconds: '{count} seconds', enlarge: '{code}: {name}. Enlarge figure.', enlargedFigure: 'Enlarged figure', close: 'Close', filterLabel: 'Filter figures', sectionsLabel: 'Sections', homeLabel: 'Dive Pool Trainer, home', loadingFailed: 'Could not load', loadingHint: 'Refresh this page when you are online again.'
  },
  nl: {
    languageLabel: 'Taal', heroEyebrow: 'TRAIN JE WEDSTRIJDGEHEUGEN', heroTitle1: 'Zie de code.', heroTitle2: 'Ken de sprong.', heroCopy: 'Oefen de letters, blokken en figuren van jouw dive pool. Op je telefoon, tablet of computer.',
    tabTrain: 'Oefenen', tabLibrary: 'Figurenoverzicht', tabSettings: 'Instellingen', sectionTrain: '01 / OEFENEN', trainHeading: 'Jouw volgende sprong', randomCombination: 'WILLEKEURIGE COMBINATIE', revealButton: 'Toon figuren', resetButton: 'Pool opnieuw starten',
    sectionLearn: '02 / LEREN', libraryHeading: 'Figurenoverzicht', libraryCopy: 'Bekijk de naam en de tekening van iedere letter en ieder blok in de gekozen pool.', searchLabel: 'Zoek figuur of naam', searchPlaceholder: 'Zoek code of naam…', filterAll: 'Alles', filterLetters: 'Letters', filterBlocks: 'Blokken',
    sectionSettings: '03 / INSTELLINGEN', settingsHeading: 'Maak het jouw training', poolLabel: 'Dive pool', poolHelp: 'Een andere pool begint een nieuwe oefensessie.', difficultyLabel: 'Moeilijkheid', difficultyHelp: 'De combinatie loopt door tot dit aantal punten is bereikt. Een blok telt voor twee.', delayLabel: 'Vertraging figuren', delayHelp: 'Na deze tijd verschijnen de afbeeldingen vanzelf. Met “Toon figuren” kun je ze eerder zien.', saveButton: 'Instellingen opslaan', footer: 'Train zelfstandig · Geen account nodig · Werkt ook offline na het eerste bezoek',
    ready: 'Klaar voor de start', startHint: 'Druk op GO om een nieuwe combinatie te krijgen.', round: 'Ronde {count}', remaining: '{count} figuren over', target: 'Doel: {points}', poolFinished: 'Pool voltooid. Start opnieuw voor een nieuwe reeks.', rememberOne: 'Onthoud de figuur achter deze code.', rememberMany: 'Onthoud de figuren achter deze codes.', appearing: 'De figuren verschijnen zo…', shownOne: '1 figuur getoond. Tik op de afbeelding om te vergroten.', shownMany: '{count} figuren getoond. Tik op een afbeelding om te vergroten.', libraryCount: '{count} van {total} figuren', onePoint: '1 punt', manyPoints: '{count} punten', seconds: '{count} seconden', enlarge: '{code}: {name}. Vergroot figuur.', enlargedFigure: 'Vergrote figuur', close: 'Sluiten', filterLabel: 'Filter figuren', sectionsLabel: 'Onderdelen', homeLabel: 'Dive Pool Trainer, begin', loadingFailed: 'Laden mislukt', loadingHint: 'Vernieuw de pagina wanneer je weer verbinding hebt.'
  },
  fr: {
    languageLabel: 'Langue', heroEyebrow: 'ENTRAÎNEZ VOTRE MÉMOIRE DE COMPÉTITION', heroTitle1: 'Voyez le code.', heroTitle2: 'Connaissez le saut.', heroCopy: 'Entraînez-vous avec les lettres, blocs et figures de votre dive pool. Sur téléphone, tablette ou ordinateur.',
    tabTrain: 'Entraînement', tabLibrary: 'Figures', tabSettings: 'Paramètres', sectionTrain: '01 / ENTRAÎNEMENT', trainHeading: 'Votre prochain saut', randomCombination: 'COMBINAISON ALÉATOIRE', revealButton: 'Voir les figures', resetButton: 'Recommencer le pool',
    sectionLearn: '02 / APPRENDRE', libraryHeading: 'Toutes les figures', libraryCopy: 'Découvrez le nom et le dessin de chaque lettre et de chaque bloc du pool sélectionné.', searchLabel: 'Chercher une figure ou un nom', searchPlaceholder: 'Chercher un code ou un nom…', filterAll: 'Tout', filterLetters: 'Lettres', filterBlocks: 'Blocs',
    sectionSettings: '03 / PARAMÈTRES', settingsHeading: 'Personnalisez votre entraînement', poolLabel: 'Dive pool', poolHelp: 'Changer de pool lance une nouvelle séance.', difficultyLabel: 'Difficulté', difficultyHelp: 'La combinaison continue jusqu’à atteindre ce nombre de points. Un bloc vaut deux points.', delayLabel: 'Délai des figures', delayHelp: 'Les images apparaissent automatiquement après ce délai. Vous pouvez les afficher plus tôt.', saveButton: 'Enregistrer', footer: 'Entraînement individuel · Sans compte · Fonctionne hors ligne après la première visite',
    ready: 'Prêt à commencer', startHint: 'Appuyez sur GO pour obtenir une combinaison.', round: 'Tour {count}', remaining: '{count} figures restantes', target: 'Objectif : {points}', poolFinished: 'Pool terminé. Recommencez pour une nouvelle série.', rememberOne: 'Retenez la figure correspondant à ce code.', rememberMany: 'Retenez les figures correspondant à ces codes.', appearing: 'Les figures apparaîtront bientôt…', shownOne: '1 figure affichée. Touchez l’image pour l’agrandir.', shownMany: '{count} figures affichées. Touchez une image pour l’agrandir.', libraryCount: '{count} figures sur {total}', onePoint: '1 point', manyPoints: '{count} points', seconds: '{count} secondes', enlarge: '{code} : {name}. Agrandir la figure.', enlargedFigure: 'Figure agrandie', close: 'Fermer', filterLabel: 'Filtrer les figures', sectionsLabel: 'Sections', homeLabel: 'Dive Pool Trainer, accueil', loadingFailed: 'Chargement impossible', loadingHint: 'Actualisez la page quand vous serez à nouveau en ligne.'
  },
  de: {
    languageLabel: 'Sprache', heroEyebrow: 'TRAINIERE DEIN WETTKAMPFGEDÄCHTNIS', heroTitle1: 'Sieh den Code.', heroTitle2: 'Kenn den Sprung.', heroCopy: 'Übe Buchstaben, Blöcke und Formationen deines Dive Pools. Auf Handy, Tablet oder Computer.',
    tabTrain: 'Trainieren', tabLibrary: 'Figuren', tabSettings: 'Einstellungen', sectionTrain: '01 / TRAINIEREN', trainHeading: 'Dein nächster Sprung', randomCombination: 'ZUFÄLLIGE KOMBINATION', revealButton: 'Figuren zeigen', resetButton: 'Pool neu starten',
    sectionLearn: '02 / LERNEN', libraryHeading: 'Figurenübersicht', libraryCopy: 'Entdecke Name und Zeichnung jedes Buchstabens und Blocks im gewählten Pool.', searchLabel: 'Figur oder Namen suchen', searchPlaceholder: 'Code oder Namen suchen…', filterAll: 'Alle', filterLetters: 'Buchstaben', filterBlocks: 'Blöcke',
    sectionSettings: '03 / EINSTELLUNGEN', settingsHeading: 'Gestalte dein Training', poolLabel: 'Dive Pool', poolHelp: 'Ein anderer Pool startet eine neue Trainingseinheit.', difficultyLabel: 'Schwierigkeit', difficultyHelp: 'Die Kombination läuft bis zur gewählten Punktzahl. Ein Block zählt zwei Punkte.', delayLabel: 'Verzögerung der Figuren', delayHelp: 'Die Bilder erscheinen nach dieser Zeit automatisch. Du kannst sie früher anzeigen.', saveButton: 'Einstellungen speichern', footer: 'Alleine trainieren · Kein Konto nötig · Nach dem ersten Besuch offline nutzbar',
    ready: 'Bereit zum Start', startHint: 'Drücke GO für eine neue Kombination.', round: 'Runde {count}', remaining: '{count} Figuren übrig', target: 'Ziel: {points}', poolFinished: 'Pool abgeschlossen. Starte für eine neue Serie erneut.', rememberOne: 'Merke dir die Figur hinter diesem Code.', rememberMany: 'Merke dir die Figuren hinter diesen Codes.', appearing: 'Die Figuren erscheinen gleich…', shownOne: '1 Figur angezeigt. Tippe auf das Bild zum Vergrößern.', shownMany: '{count} Figuren angezeigt. Tippe auf ein Bild zum Vergrößern.', libraryCount: '{count} von {total} Figuren', onePoint: '1 Punkt', manyPoints: '{count} Punkte', seconds: '{count} Sekunden', enlarge: '{code}: {name}. Figur vergrößern.', enlargedFigure: 'Vergrößerte Figur', close: 'Schließen', filterLabel: 'Figuren filtern', sectionsLabel: 'Bereiche', homeLabel: 'Dive Pool Trainer, Startseite', loadingFailed: 'Laden fehlgeschlagen', loadingHint: 'Lade die Seite neu, sobald du wieder online bist.'
  },
  uk: {
    languageLabel: 'Мова', heroEyebrow: 'ТРЕНУЙТЕ ПАМʼЯТЬ ДЛЯ ЗМАГАНЬ', heroTitle1: 'Бачте код.', heroTitle2: 'Знайте стрибок.', heroCopy: 'Вивчайте літери, блоки та фігури свого дайв-пулу. На телефоні, планшеті чи компʼютері.',
    tabTrain: 'Тренування', tabLibrary: 'Фігури', tabSettings: 'Налаштування', sectionTrain: '01 / ТРЕНУВАННЯ', trainHeading: 'Ваш наступний стрибок', randomCombination: 'ВИПАДКОВА КОМБІНАЦІЯ', revealButton: 'Показати фігури', resetButton: 'Почати пул спочатку',
    sectionLearn: '02 / ВИВЧЕННЯ', libraryHeading: 'Каталог фігур', libraryCopy: 'Перегляньте назву й зображення кожної літери та блоку у вибраному пулі.', searchLabel: 'Знайти фігуру або назву', searchPlaceholder: 'Пошук коду або назви…', filterAll: 'Усі', filterLetters: 'Літери', filterBlocks: 'Блоки',
    sectionSettings: '03 / НАЛАШТУВАННЯ', settingsHeading: 'Налаштуйте тренування', poolLabel: 'Дайв-пул', poolHelp: 'Зміна пулу починає нове тренування.', difficultyLabel: 'Складність', difficultyHelp: 'Комбінація триває до досягнення цієї кількості очок. Блок дає два очки.', delayLabel: 'Затримка показу фігур', delayHelp: 'Зображення зʼявляться автоматично після затримки. Їх можна показати раніше.', saveButton: 'Зберегти налаштування', footer: 'Індивідуальне тренування · Без облікового запису · Працює офлайн після першого відвідування',
    ready: 'Готові до старту', startHint: 'Натисніть GO, щоб отримати нову комбінацію.', round: 'Раунд {count}', remaining: 'Залишилось фігур: {count}', target: 'Мета: {points}', poolFinished: 'Пул завершено. Почніть знову для нової серії.', rememberOne: 'Запамʼятайте фігуру за цим кодом.', rememberMany: 'Запамʼятайте фігури за цими кодами.', appearing: 'Фігури незабаром зʼявляться…', shownOne: 'Показано 1 фігуру. Натисніть на зображення, щоб збільшити.', shownMany: 'Показано фігур: {count}. Натисніть на зображення, щоб збільшити.', libraryCount: 'Фігур: {count} із {total}', onePoint: '1 бал', fewPoints: '{count} бали', manyPoints: '{count} балів', seconds: '{count} с', enlarge: '{code}: {name}. Збільшити фігуру.', enlargedFigure: 'Збільшена фігура', close: 'Закрити', filterLabel: 'Фільтр фігур', sectionsLabel: 'Розділи', homeLabel: 'Dive Pool Trainer, головна', loadingFailed: 'Не вдалося завантажити', loadingHint: 'Оновіть сторінку, коли знову будете онлайн.'
  }
};

DICTIONARIES['nl-BE'] = {
  ...DICTIONARIES.nl,
  heroEyebrow: 'TRAIN UW WEDSTRIJDGEHEUGEN',
  heroCopy: 'Oefen de letters, blokken en figuren van uw dive pool. Op uw gsm, tablet of computer.',
  trainHeading: 'Uw volgende sprong',
  settingsHeading: 'Stel uw training in',
  poolHelp: 'Een andere pool start een nieuwe oefensessie.',
  saveButton: 'Instellingen bewaren',
  startHint: 'Druk op GO voor een nieuwe combinatie.',
};

window.DivePoolI18n = { TRANSLATIONS: DICTIONARIES };
